defaults: &defaults
  FACEBOOK_APP_ID: 267267416716973
  FACEBOOK_APP_SECRET: 71cbfaa54dee1b083efa6339a558be56
  SITE_URL: localhost:3000

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  FACEBOOK_APP_ID: 267267416716973
  FACEBOOK_APP_SECRET: 71cbfaa54dee1b083efa6339a558be56
  SITE_URL: bh-mapmyfriends.herokuapp.com